PrjSistemaFinanceiro/PrjSistemaFinanceiro/Controllers/VendedorController.cs
using Model.Entity;
using Model.Neg;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrjSistemaFinanceiro.Controllers
{
    public class VendedorController : Controller
    {
        VendedorNeg objVendedorNeg;
        
        public VendedorController()
        {
            objVendedorNeg = new VendedorNeg(); 
        }

        public ActionResult Index()
        {
            List<Vendedor> lista = objVendedorNeg.findAll();
            return View(lista);
        }
    }
}

PrjSistemaFinanceiro/PrjSistemaFinanceiro/Views/Shared/_Layout.cshtml
@{
    ViewBag.Title = "Sistema Financeiro";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Principal- Sistema Financeiro</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <!-- MetisMenu CSS -->
    <link href="~/Assets/metisMenu/metisMenu.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Css/sb-admin-2.css" rel="stylesheet" />
    <!-- Morris Charts CSS -->
    <link href="~/Assets/morrisjs/morris.css" rel="stylesheet" />
    <!-- Custom Fonts -->
    <link href="~/Assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
   <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
   
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">              
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-home fa-fw"></i> INICIO
                    </a>
                    <!-- /.dropdown-tasks -->
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-home fa-fw"></i> QUEM SOMOS
                    </a>
                    <!-- /.dropdown-tasks -->
                </li>
                
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell fa-fw"></i>SERVIÇOS <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href="~/Cliente/Index">
                                <div>
                                    <i class="fa fa-users fa-fw"></i>Cadastrar Clientes
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-users fa-fw"></i> Cadastrar Vendedor
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-book fa-fw"></i> Inserir Info
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-tv fa-fw"></i> Inserir Info
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <div>
                                    <i class="fa fa-shopping-cart fa-fw"></i>Inserir Info
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                       
                    </ul>
                    <!-- /.dropdown-alerts -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> Usuários</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Configurações</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#"><i class="fa fa-sign-out fa-fw"></i> Sair</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="~/"><i class="fa fa-home fa-fw"></i> Principal</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-car fa-fw"></i> Produtos<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/Categoria/Index"><i class="fa fa-check fa-fw" style="color:#f0ad4e"></i>Categorías</a>
                                </li>
                                <li>
                                    <a href="~/Producto/BuscarProdutos"><i class="fa fa-search fa-fw" style="color:#f0ad4e"></i>Buscar Produto</a>
                                </li>
                               
                                <li>
                                    <a href="~/Produto/Index"><i class="fa fa-product-hunt fa-fw" style="color:#f0ad4e"></i>Produto</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-sort-numeric-asc fa-fw" style="color:#f0ad4e"></i>Estoque</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Vendas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/Venda/VendaFatura"><i class="fa fa-archive fa-fw" style="color:#f0ad4e"></i>Fatura</a>
                                </li>
                                <li>
                                    <a href="~/Venda/NovaVenda"><i class="fa fa-shopping-cart fa-fw" style="color:#f0ad4e"></i>Nova Venda</a>
                                </li>
                                <li>
                                    <a href="~/DetalheVenda/Index"><i class="fa fa-info-circle fa-fw" style="color:#f0ad4e"></i>Detalhe Vendas</a>
                                </li>
                                <li>
                                    <a href="~/Venda/RelatorioVendas"><i class="fa fa-book fa-fw" style="color:#f0ad4e"></i>Relatórios</a>
                                </li>
                                
                            </ul>
                        </li>
                        <li>
                            <a href="~/Cliente/Index"><i class="fa fa-user fa-fw"></i> Clientes</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Vendedor")"><i class="fa fa-user fa-fw"></i> Vendedores</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> PGTs e Cobranças<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="~/ModoPag/Index"><i class="fa fa-dollar fa-fw"  style="color:#f0ad4e"></i>Forma Pgto</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-dollar fa-fw"  style="color:#f0ad4e"></i>Pagamentos</a>
                                </li>
                                <li>
                                    <a href="#"><i class="fa fa-dollar fa-fw"  style="color:#f0ad4e"></i>Cobranças</a>
                                </li>
                                
                            </ul>
                        </li>

                        <li>
                            <a href="#"><i class="fa fa-wrench fa-fw"></i> Administração<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Empresa</a>
                                </li>
                                <li>
                                    <a href="#">Funcionários</a>
                                </li>
                                <li>
                                    <a href="#">Estoque</a>
                                </li>
                                <li>
                                    <a href="#">Cargos</a>
                                </li>
                                <li>
                                    <a href="#"> Usuarios</a>
                                </li>

                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">           
            <!-- /.row -->
           
            <div class="row">
                @RenderBody()
            </div>

        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Assets/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Assets/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Assets/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    
    <script src="~/Assets/morrisjs/morris.min.js"></script>    
   
    <!-- Custom Theme JavaScript -->
    <script src="~/Js/sb-admin-2.js"></script>
   
 
</body>
</html>